class LoginPageLocators:
    LOGIN_FIELD = '//*[@id="field_email"]'
    PASSWORD_FIELD = '//*[@id="field_password"]'
    ENTER_BUTTON = '//*[@data-l="t,sign_in"]'
    QR_LINK = '//*["@data-l="t,get_qr"]'
    REGISTER_LINK = '//*[@data-l="t,register"]'
    VK_LINK = '//*[@data-l="t,vkc"]'
    MAIL_LINK = '//*[@data-l="t,mailru"]'
    GOOGLE_LINK = '//*[@data-l="t,google"]'
    YANDEX_LINK = '//*[data-l="t,yandex"]'
    APPLE_LINK = '//*[@data-l="t,apple"]'
    ENTER_TAB_LINK = '//*[@data-l="t,login_tab"]'
    QR_TAB_LINK = '//*[@data-l="t,qr_tab"]'